name: CloudShop DevSecOps Pipeline

# --------------------------------------------------
# REQUIRED PERMISSIONS (Fix CodeQL Warning)
# --------------------------------------------------
permissions:
  contents: read
  security-events: write
  actions: read

# --------------------------------------------------
# TRIGGERS
# --------------------------------------------------
on:
  push:
    branches: [ main ]
  pull_request:

env:
  IMAGE_NAME: cloudshop

# ==================================================
# JOB 1 — LINT + CODE QUALITY
# ==================================================
jobs:

  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Run Lint Check
        run: flake8 src/

# ==================================================
# JOB 2 — SAST SECURITY SCAN (CodeQL)
# ==================================================

  security-scan:
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

# ==================================================
# JOB 3 — DOCKER BUILD + TRIVY SCAN (DevSecOps)
# ==================================================

  docker-build-scan:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # -----------------------------
      # Build Docker Image
      # -----------------------------
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      # -----------------------------
      # Container Vulnerability Scan
      # -----------------------------
      - name: Scan Image using Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cloudshop:${{ github.sha }}
          format: table
          exit-code: 0   ## if this is 0 then it will skip otherwise it will fail because of vulnerabilities found
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

# ==================================================
# JOB 4 — PUSH IMAGE TO AWS ECR
# ==================================================

  push-ecr:
    runs-on: ubuntu-latest
    needs: docker-build-scan

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-2 \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Build and Push Image
        run: |
          docker build -t cloudshop:${{ github.sha }} .
          docker tag cloudshop:${{ github.sha }} ${{ secrets.ECR_REPO }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPO }}:${{ github.sha }}

# ==================================================
# JOB 5 — GITOPS UPDATE (ARGOCD TRIGGER)
# ==================================================

  gitops-update:
    runs-on: ubuntu-latest
    needs: push-ecr

    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: Abhilash-1201/poc-cloudshop-gitops
          token: ${{ secrets.GH_PAT }}

      - name: Update Image Tag
        run: |
          sed -i 's|tag:.*|tag: "${{ github.sha }}"|' dev/values.yaml

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tag ${{ github.sha }}"
          git push

          