name: CloudShop DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

env:
  IMAGE_NAME: cloudshop

jobs:

# -------------------------------
# 1. CODE QUALITY CHECK
# -------------------------------
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Lint Code
        run: flake8 src/

# -------------------------------
# 2. SECURITY SCANNING (DevSecOps)
# -------------------------------
  security-scan:
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
      - uses: actions/checkout@v4

      - name: Run CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - uses: github/codeql-action/analyze@v3

# -------------------------------
# 3. DOCKER BUILD
# -------------------------------
  docker-build:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

# -------------------------------
# 4. CONTAINER SECURITY SCAN
# -------------------------------
  image-scan:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - uses: actions/checkout@v4

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cloudshop:${{ github.sha }}

# -------------------------------
# 5. PUSH TO AWS ECR
# -------------------------------
  push-ecr:
    runs-on: ubuntu-latest
    needs: image-scan

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-west-2 \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Build & Push
        run: |
          docker build -t cloudshop:${{ github.sha }} .
          docker tag cloudshop:${{ github.sha }} ${{ secrets.ECR_REPO }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPO }}:${{ github.sha }}

# -------------------------------
# 6. GITOPS UPDATE
# -------------------------------
  gitops-update:
    runs-on: ubuntu-latest
    needs: push-ecr

    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: Abhilash-1201/poc-cloudshop-gitops
          token: ${{ secrets.GH_PAT }}

      - name: Update Image Tag
        run: |
          sed -i 's|tag:.*|tag: "${{ github.sha }}"|' dev/values.yaml

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tag"
          git push
